### ISSUE TITLE
line 6: [: -v: unary operator expected

### ISSUE THREAD

**Issue by eboelens** [mrrfv/linux-android-backup#57] opened 2023-04-25 07:39 UTC
## Device info

Manufacturer: Asus
Android version: A12
Custom ROM/rooted? /e/ yes
Model: Sake

## System info

Available disk space: 500GB
Operating system: OSX 10.15.7 ( Homebrew and Apple do not provide support for this old version)

---

**Describe the issue below.**
when run the script sh backup.sh:

line 6: [: -v: unary operator expected

**Comment by mrrfv** [comment] 2023-04-26 04:40
This error is caused by the version of Bash shipped by Apple, which is very outdated. Homebrew is required to download the latest Bash and other needed dependencies, so the script won't work without it.

Won't fix.

**Comment by eboelens** [comment] 2023-04-26 15:53
ok Thanks
With Linux Ubuntu it works until the companion app wont install I think, I will see later

**Closed** 2023-04-27 17:31 UTC
Labels: bug
